#!/bin/sh

JAVALIB=/segfs/tango/release/java/lib/hdb

CLASSPATH=.
CLASSPATH=$CLASSPATH:$JAVALIB/cassandra-driver-core-2.1.6.jar
CLASSPATH=$CLASSPATH:$JAVALIB/guava-14.0.1.jar
CLASSPATH=$CLASSPATH:$JAVALIB/lz4-1.2.0.jar
CLASSPATH=$CLASSPATH:$JAVALIB/metrics-core-3.0.2.jar
CLASSPATH=$CLASSPATH:$JAVALIB/mysql-connector-java-5.1.31-bin.jar
CLASSPATH=$CLASSPATH:$JAVALIB/netty-buffer-4.0.27.Final.jar
CLASSPATH=$CLASSPATH:$JAVALIB/netty-codec-4.0.27.Final.jar
CLASSPATH=$CLASSPATH:$JAVALIB/netty-common-4.0.27.Final.jar
CLASSPATH=$CLASSPATH:$JAVALIB/netty-handler-4.0.27.Final.jar
CLASSPATH=$CLASSPATH:$JAVALIB/netty-transport-4.0.27.Final.jar
CLASSPATH=$CLASSPATH:$JAVALIB/slf4j-api-1.7.12.jar
CLASSPATH=$CLASSPATH:$JAVALIB/slf4j-simple-1.7.12.jar
CLASSPATH=$CLASSPATH:$JAVALIB/lz4-1.2.0.jar

export CLASSPATH
echo $CLASSPATH

java org.tango.jhdbextract.HdbExtractor
