
package org.tango.hdb_configurator.common;

/**
 *	HTML code to display Release Notes for this package.
 *	It is generated by Pogo classes from a text file.
 */

public interface ReleaseNote
{
	public final String	str = 
		"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 3.2//EN\">\n" + 
		"<HTML>\n" + 
		"<HEAD>\n" + 
		"<Title> Release Note </Title>\n" + 
		"</HEAD>\n" + 
		"<BODY TEXT=\"#000000\" BGCOLOR=\"#FFFFFF\" LINK=\"#0000FF\" VLINK=\"#7F00FF\" ALINK=\"#FF0000\">\n" + 
		"<P><!-------TITLE------></P>\n" + 
		"<Center>	<h2>org.tango.hdb_configurator.tools Release Note</h2>\n" + 
		"	(Generated Mon Jun 06 08:13:41 CEST 2016)</Center><Br>\n" + 
		"<li><b>hdb_configurator-1.3 - 06/06/16:</b><Br>\n" + 
		"&nbsp; &nbsp; Fix a problem on default TANO_HOST<Br>\n" + 
		"<li><b>hdb_configurator-1.2 - 27/05/16:</b><Br>\n" + 
		"&nbsp; &nbsp; Fix a problem for DevFailed/NamedDevFailedList exception<Br>\n" + 
		"<li><b>hdb_configurator-1.1 - 13/05/16:</b><Br>\n" + 
		"&nbsp; &nbsp; Fix problem of refreshing in attribute tree.<Br>\n" + 
		"<li><b>hdb_configurator-1.0 - 12/05/16:</b><Br>\n" + 
		"&nbsp; &nbsp; Change package name (reset revision number)<Br>\n" + 
		"<li><b>jhdbcpp-2.7 - 03/05/16:</b><Br>\n" + 
		"&nbsp; &nbsp; few methods added for external class.<Br>\n" + 
		"<li><b>jhdbcpp-2.6 - 19/12/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Remove event tester launch in StatisticsDialog menu (does not work fine).<Br>\n" + 
		"<li><b>jhdbcpp-2.5 - 16/12/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Fix a problem when moving paused attributes<Br>\n" + 
		"<li><b>jhdbcpp-2.4 - 26/11/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Refactor to remove cross links.<Br>\n" + 
		"<li><b>jhdbcpp-2.3 - 26/11/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Interface with jhdbvewer to read attribute in hdb.<Br>\n" + 
		"<li><b>jhdbcpp-2.2 - 24/09/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Fix a little bug on plain/bold attribute display<Br>\n" + 
		"<li><b>jhdbcpp-2.1 - 19/05/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Subscriber alias management added.<Br>\n" + 
		"&nbsp; &nbsp; Performance view added in distribution<Br>\n" + 
		"&nbsp; &nbsp; Compatibility with Java-7<Br>\n" + 
		"<li><b>jhdbcpp-2.0 - 23/04/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Change GUI look and feel.<Br>\n" + 
		"&nbsp; &nbsp; Add pause attribute state.<Br>\n" + 
		"&nbsp; &nbsp; Attribute lists are updated from events<Br>\n" + 
		"<li><b>jhdbcpp-1.13 - 08/04/15:</b><Br>\n" + 
		"&nbsp; &nbsp; small chamges.<Br>\n" + 
		"<li><b>jhdbcpp-1.12 - 03/03/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Info on attribute failure frequency and on E.S. manager added.<Br>\n" + 
		"&nbsp; &nbsp; Trend on HDB storage frequency added.<Br>\n" + 
		"<li><b>jhdbcpp-1.11 - 06/02/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Add a table to view all attribues on error.<Br>\n" + 
		"<li><b>jhdbcpp-1.10 - 20/01/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Table added to distribution dialog<Br>\n" + 
		"<li><b>jhdbcpp-1.9 - 16/01/15:</b><Br>\n" + 
		"&nbsp; &nbsp; Events number added to distribution chart.<Br>\n" + 
		"<li><b>jhdbcpp-1.8 - 19/12/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Improve attribute error window.<Br>\n" + 
		"&nbsp; &nbsp; Add a selector to change TANGO_HOST<Br>\n" + 
		"&nbsp; &nbsp; Event tester call added.<Br>\n" + 
		"<li><b>jhdbcpp-1.7 - 06/11/14:</b><Br>\n" + 
		"&nbsp; &nbsp; FQDN event subscriber name to be added to manager.<Br>\n" + 
		"&nbsp; &nbsp; Events since reset added.<Br>\n" + 
		"&nbsp; &nbsp; Save statistics added.<Br>\n" + 
		"<li><b>jhdbcpp-1.6 - 30/10/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Display event frequency added.<Br>\n" + 
		"<li><b>jhdbcpp-1.5 - 13/10/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Display error message on failed attribute list.<Br>\n" + 
		"&nbsp; &nbsp; Display HDB name if property set.<Br>\n" + 
		"<li><b>jhdbcpp-1.4 - 24/09/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Diag viewers are now in a JTable object.<Br>\n" + 
		"&nbsp; &nbsp; A double click on table cell displays attribute list.<Br>\n" + 
		"<li><b>jhdbcpp-1.3 - 22/09/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Fix a bug in archiver device creation<Br>\n" + 
		"<li><b>jhdbcpp-1.2 - 05/09/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Add a graph chart to display distribution.<Br>\n" + 
		"<li><b>jhdbcpp-1.1 - 28/08/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Add/Remove subscriber added.<Br>\n" + 
		"<li><b>jhdbcpp-1.0 - 06/08/14:</b><Br>\n" + 
		"&nbsp; &nbsp; Initial Revision<Br>\n" + 
		"</Body>\n" + 
		"</Html>\n" + 
		"";
}
