/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HDBViewer;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JScrollPane;

/**
 *
 * @author pons
 */
public class TablePanel extends javax.swing.JPanel {

  MainPanel parent;
  MultiLineTable table;
  JScrollPane tableView;

  /**
   * Creates new form TablePanel
   */
  TablePanel(MainPanel parent) {

    this.parent = parent;
    initComponents();
    
    table = new MultiLineTable();
    tableView = new JScrollPane(table);
    tablePanel.add(tableView, BorderLayout.CENTER);
    setPreferredSize(new Dimension(800, 600));
    
  }
  


  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    tablePanel = new javax.swing.JPanel();
    tableBtnPanel = new javax.swing.JPanel();
    doMicroCheck = new javax.swing.JCheckBox();
    saveButton = new javax.swing.JButton();
    copyButton = new javax.swing.JButton();

    setLayout(new java.awt.BorderLayout());

    tablePanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    tablePanel.setLayout(new java.awt.BorderLayout());
    add(tablePanel, java.awt.BorderLayout.CENTER);

    tableBtnPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 5, 1));

    doMicroCheck.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    doMicroCheck.setText("Display microseconds");
    doMicroCheck.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        doMicroCheckActionPerformed(evt);
      }
    });
    tableBtnPanel.add(doMicroCheck);

    saveButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    saveButton.setText("Save file");
    saveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveButtonActionPerformed(evt);
      }
    });
    tableBtnPanel.add(saveButton);

    copyButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
    copyButton.setText("Copy Selection");
    copyButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        copyButtonActionPerformed(evt);
      }
    });
    tableBtnPanel.add(copyButton);

    add(tableBtnPanel, java.awt.BorderLayout.SOUTH);
  }// </editor-fold>//GEN-END:initComponents

  private void doMicroCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doMicroCheckActionPerformed

    table.doMicroSec(doMicroCheck.isSelected());

  }//GEN-LAST:event_doMicroCheckActionPerformed

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed

    JFileChooser chooser = new JFileChooser(".");
    if (chooser.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
      try {
        table.saveFile(chooser.getSelectedFile().getAbsolutePath());
      } catch(IOException e) {
        Utils.showError(e.getMessage());
      }
    }
    
  }//GEN-LAST:event_saveButtonActionPerformed

  private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed

    StringSelection stringSelection = new StringSelection( table.getSelectionAsString() );
    Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
    clipboard.setContents( stringSelection, null );
    
  }//GEN-LAST:event_copyButtonActionPerformed


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton copyButton;
  private javax.swing.JCheckBox doMicroCheck;
  private javax.swing.JButton saveButton;
  private javax.swing.JPanel tableBtnPanel;
  private javax.swing.JPanel tablePanel;
  // End of variables declaration//GEN-END:variables
}
